apiVersion: v1
kind: Pod
metadata:
  name: giropops-1
  labels:
    run: giropops-1
spec:
  containers:
  - name: girus
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "300m"
