apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops-0
  name: giropops-0
spec:
  containers:
  - name: girus
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "300m"
  - name: strigus
    image: alpine
    args:
    - sleep
    - "1800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
