apiVersion: v1
kind: Pod
metadata:
  name: pod-service-account
  namespace: default
spec:
  serviceAccountName: service-account-example
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["sleep", "infinity"]